name: Build & Publish
env:
  # tells the build to do full link optimization
  CI: true
on:
  push:
    # tags:
    #   - v*
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # `get-name` won't work until https://github.com/com-lihaoyi/mill/pull/4418 is released
      # instead, manually pass the path into the upload-artifact action
      # - id: get-name
      #   run: echo "bin_name=$(./mill showNamed find.linkRename | jq -r '."find.linkRename"')" >> $GITHUB_OUTPUT
      - run: ./mill show _.linkRename
      - uses: actions/upload-artifact@v4
        with:
          name: find-projects
          # path: ${{ steps.get-name.outputs.exec_name }}
          path: out/find/nativeLink.dest/find-projects
          overwrite: true
      - uses: actions/upload-artifact@v4
        with:
          name: sc
          # path: ${{ steps.get-name.outputs.exec_name }}
          path: out/sc/nativeLink.dest/sc
          overwrite: true
