name: Build & Publish
env:
  CI: true
on:
  push:
    # tags:
    #   - v*
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./mill --disable-prompt showNamed fsp.linkRename 2>/dev/null
      # - run: echo "exec_name=$(./mill --disable-prompt showNamed fsp.linkRename 2>/dev/null | jq  '."fsp.linkRename"')" >> $GITHUB_OUTPUT
      #   id: get-name
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: find-scala-projects
      #     path: ${{ steps.get-name.outputs.exec_name }}
      #     overwrite: true
