name: Build & Publish
on:
  push:
    # tags:
    #   - v*
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./mill show fsp.nativeLink
      - run: ls -l ./out/fsp/nativeLink.dest/out
      - uses: actions/upload-artifact@v4
        with:
          name: find-scala-projects
          path: ./out/fsp/nativeLink.dest/out
          overwrite: true
