name: Build & Publish
env:
  CI: true
on:
  push:
    # tags:
    #   - v*
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "exec_name=$(./mill show fsp.linkRename 2>/dev/null)" >> $GITHUB_OUTPUT
        id: get-name
      - uses: actions/upload-artifact@v4
        with:
          name: find-scala-projects
          path: steps.get-name.outputs.exec_name
          overwrite: true
