name: Build & Publish
# env:
#   CI: true
on:
  push:
    # tags:
    #   - v*
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # `get-name` won't work until https://github.com/com-lihaoyi/mill/pull/4418 is released
      # instead, manually pass the path into the upload-artifact action
      # - id: get-name
      #   run: echo "bin_name=$(./mill showNamed fsp.linkRename | jq -r '."fsp.linkRename"')" >> $GITHUB_OUTPUT
      - run: ./mill show fsp.linkRename
      - uses: actions/upload-artifact@v4
        with:
          name: find-scala-projects
          # path: ${{ steps.get-name.outputs.exec_name }}
          path: out/fsp/nativeLink.dest/find-scala-projects
          overwrite: true
